Classification:
  EYEPACS: '/home/clement/Documents/data/eyepacs/'
  APTOS: '/home/clement/Documents/data/aptos/'
  DDR: '/home/clement/Documents/data/DDR/DDR-dataset/DR_grading/'
  IDRID: '/home/clement/Documents/data/IDRID/B. Disease Grading/' 

Segmentation:
  IDRID: '/home/clement/Documents/data/IDRID/A. Segmentation/'
  DDR: '/home/clement/Documents/data/DDR/DDR-dataset/lesion_segmentation/'
  MESSIDOR: '/home/clement/Documents/data/Maples-DR/'
  FGADR: '/home/clement/Documents/data/FGADR/Seg-set/'
  RETLES: '/home/clement/Documents/data/retinal-lesions-v20191227/'
